class ProdutoModel {
  String? descricaoPdv;
  String? ean;
  String? codIntNaoUsar;
  String? cfop;
  String? eantrib;
  String? csosn;
  String? calcularIcmsSt;
  String? reducaoIcms;
  String? cofinsntCst;
  String? pisNtCst;
  String? icmsOrigem;
  String? codigoEnquadramento;
  String? ipintCst;
  String? ncm;
  String? unidade;
  String? cest;
  String? referencia;
  String? pesoLiquido;
  String? pesoBruto;
  String? precoPadrao;
  String? precoAVistaNaoUsar;
  String? precoAPrazo;
  String? precoAVista;
  String? precoPromocional;
  String? idProduto;
  String? idEmpresa;
  String? balanca;
  String? balancaTipo;
  String? fcp;
  String? padraoImportacao;
  String? icms;
  String? produtoInativo;
  String? precoEditavel;
  String? enviarApp;
  String? atacado;
  String? codigoInterno;
  String? foto;

  ProdutoModel();

  ProdutoModel.fromJson(Map<String, dynamic> json) {
    descricaoPdv = json['descricao_pdv']?.toString();
    ean = json['ean']?.toString();
    codIntNaoUsar = json['cod_int_nao_usar']?.toString();
    cfop = json['cfop']?.toString();
    eantrib = json['eantrib']?.toString();
    csosn = json['csosn']?.toString();
    calcularIcmsSt = json['calcular_icms_st']?.toString();
    reducaoIcms = json['reducao_icms']?.toString();
    cofinsntCst = json['cofinsnt_cst']?.toString();
    pisNtCst = json['pis_nt_cst']?.toString();
    icmsOrigem = json['icms_origem']?.toString();
    codigoEnquadramento = json['codigo_enquadramento']?.toString();
    ipintCst = json['ipint_cst']?.toString();
    ncm = json['ncm']?.toString();
    unidade = json['unidade']?.toString();
    cest = json['cest']?.toString();
    referencia = json['referencia']?.toString();
    pesoLiquido = json['peso_liquido']?.toString();
    pesoBruto = json['peso_bruto']?.toString();
    precoPadrao = json['preco_padrao']?.toString();
    precoAVistaNaoUsar = json['preco_a_vista_nao_usar']?.toString();
    precoAPrazo = json['preco_a_prazo']?.toString();
    precoAVista = json['preco_a_vista']?.toString();
    precoPromocional = json['preco_promocional']?.toString();
    idProduto = json['id_produto']?.toString();
    idEmpresa = json['id_empresa']?.toString();
    balanca = json['balanca']?.toString();
    balancaTipo = json['balanca_tipo']?.toString();
    fcp = json['fcp']?.toString();
    padraoImportacao = json['padrao_importacao']?.toString();
    icms = json['icms']?.toString();
    produtoInativo = json['produto_inativo']?.toString();
    precoEditavel = json['preco_editavel']?.toString();
    enviarApp = json['enviar_app']?.toString();
    atacado = json['atacado']?.toString();
    codigoInterno = json['codigo_interno']?.toString();
    foto = json['foto']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['descricao_pdv'] = descricaoPdv;
    data['ean'] = ean;
    data['cod_int_nao_usar'] = codIntNaoUsar;
    data['cfop'] = cfop;
    data['eantrib'] = eantrib;
    data['csosn'] = csosn;
    data['calcular_icms_st'] = calcularIcmsSt;
    data['reducao_icms'] = reducaoIcms;
    data['cofinsnt_cst'] = cofinsntCst;
    data['pis_nt_cst'] = pisNtCst;
    data['icms_origem'] = icmsOrigem;
    data['codigo_enquadramento'] = codigoEnquadramento;
    data['ipint_cst'] = ipintCst;
    data['ncm'] = ncm;
    data['unidade'] = unidade;
    data['cest'] = cest;
    data['referencia'] = referencia;
    data['peso_liquido'] = pesoLiquido;
    data['peso_bruto'] = pesoBruto;
    data['preco_padrao'] = precoPadrao;
    data['preco_a_vista_nao_usar'] = precoAVistaNaoUsar;
    data['preco_a_prazo'] = precoAPrazo;
    data['preco_a_vista'] = precoAVista;
    data['preco_promocional'] = precoPromocional;
    data['id_produto'] = idProduto;
    data['id_empresa'] = idEmpresa;
    data['balanca'] = balanca;
    data['balanca_tipo'] = balancaTipo;
    data['fcp'] = fcp;
    data['padrao_importacao'] = padraoImportacao;
    data['icms'] = icms;
    data['produto_inativo'] = produtoInativo;
    data['preco_editavel'] = precoEditavel;
    data['enviar_app'] = enviarApp;
    data['atacado'] = atacado;
    data['codigo_interno'] = codigoInterno;
    data['foto'] = foto;
    return data;
  }
}
